# Generated by Django 4.1.4 on 2023-01-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='image',
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
