# Generated by Django 4.1.4 on 2023-02-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_jobmodel_point_jobmodel_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='last_date',
            field=models.DateTimeField(),
        ),
    ]
