# Generated by Django 4.1.4 on 2023-01-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_candidateapplymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='campany',
            new_name='company',
        ),
    ]
