# Generated by Django 4.1.4 on 2023-01-05 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0004_rename_campany_jobmodel_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplymodel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='job.jobmodel'),
        ),
        migrations.AlterField(
            model_name='candidateapplymodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apply_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
